
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 4;
  public static final int TOT = 8;
  public static final int LIB = 6;
  public static final int NO = 3;
  public static final int EOF = 0;
  public static final int PT = 2;
  public static final int error = 1;
  public static final int VIRG = 5;
  public static final int FACT = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PT",
  "NO",
  "NUM",
  "VIRG",
  "LIB",
  "FACT",
  "TOT"
  };
}

